yahoojapan/yosegi

- src/main/java/jp/co/yahoo/yosegi/binary/maker/UnsafeOptimizeDumpLongColumnBinaryMaker.java
Fixed bugs.
By miscalculation error of byte array, always fail under certain conditions.
> [Yosegi-23] UnsafeOptimizeDumpLongColumnBinaryMaker has incorrect calculation of byte array length.

- src/main/java/jp/co/yahoo/yosegi/binary/maker/UnsafeOptimizeDumpStringColumnBinaryMaker.java
- src/main/java/jp/co/yahoo/yosegi/binary/maker/UnsafeOptimizeStringColumnBinaryMaker.java
StringObj holds a String or byte array internally.
The current code is converted from a String to a byte array if the inside is a byte array.
With this fix, in both cases, conversion is done once.
This class already has unit tests.
I confirmed that the result of the unit test does not change.
> [Yosegi-19] When encoding a column, converting String to byte array is unnecessary

- src/main/java/jp/co/yahoo/yosegi/compressor/BZip2CommonsCompressor.java
- src/test/java/jp/co/yahoo/yosegi/compressor/TestBZip2CommonsCompressor.java
I implemented the compression level control function in bzip2 compression class.
https://yosegi.atlassian.net/browse/YOSEGI-10
I created a unit test and checked whether the compression level setting is less than the minimum value.
> [Yosegi-21] Implement compression level optimization on bzip2.

- src/main/java/jp/co/yahoo/yosegi/binary/maker/UnsafeOptimizeLongColumnBinaryMaker.java
- src/main/java/jp/co/yahoo/yosegi/util/io/NumberToBinaryUtils.java
fix the caluculation of row size in the getIndexIntBuffer
Tested on the case that errors occurred, and confirmed that the case passed using fixed code.
> fix the caluculation of row size in the getIndexIntBuffer

- docker/Dockerfile
- docker/README.md
- docker/build.sh
- pom.xml
- src/main/java/jp/co/yahoo/yosegi/reader/YosegiSchemaFileReader.java
I created a Docker file for building.
Fixed an error that occurs in this environment.
1. "Javax.xml.ws does not exist" occurred but it was unnecessary import
2. Update maven-javadoc-plugin version
This Dockerfile has a java version of 11, but I have confirmed that it can be built in a java 8 environment.
> [Yosegi-33] Create Docker image to build

- src/main/java/jp/co/yahoo/yosegi/writer/YosegiWriter.java
The default 128 MB is too big, so I think you should reduce it to 64 MB by half.
> [Yosegi-43] Default block size is too large.

- src/main/java/jp/co/yahoo/yosegi/block/ColumnBinaryTree.java
- src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockWriter.java
Removed ByteArrayData which is a buffer of data.
This fix reduces the heap size of the block size.
Removed ByteArrayData which is a buffer of data.
This fix reduces the heap size of the block size.
> Yosegi-41 Delete data buffer at block creation.

- src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinary.java
- src/main/java/jp/co/yahoo/yosegi/block/ColumnBinaryTree.java
- src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockWriter.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/BlockIndexNode.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/ByteRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/DoubleRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/FloatRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/FullRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/IntegerRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/LongRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/ShortRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/StringRangeBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/UnsupportedBlockIndex.java
- src/test/java/jp/co/yahoo/yosegi/binary/TestColumnBinary.java
- src/test/java/jp/co/yahoo/yosegi/block/BlockTestCompressor.java
- src/test/java/jp/co/yahoo/yosegi/block/TestColumnBinaryTree.java
- src/test/java/jp/co/yahoo/yosegi/block/TestPushdownSupportedBlockWriter.java
- src/test/java/jp/co/yahoo/yosegi/blockindex/DummyBlockIndex.java
So far, we have made predictions for the block size to be created. I changed it to calculate this correctly.
This will prevent the exception due to a Buffer overflow.
I checked whether the calculation of data size was correct with the setting of uncompressed metadata.
It was confirmed in the unit test that the data size after addition and the size after the addition match, and the size after addition and the block size written out the match.
> Yosegi-57 Buffer overflow.

- src/main/java/jp/co/yahoo/yosegi/util/io/NumberToBinaryUtils.java
- src/test/java/jp/co/yahoo/yosegi/util/io/TestNumberToBinaryUtils.java
The bug has been fixed.
The current code is corrupted when written.
I created a unit test and tried writing and reading all ranges.
> YOSEGI-62 Data corruption during the range of bytes with NumberToBinaryUtils

- src/main/java/jp/co/yahoo/yosegi/compressor/AbstractCommonsCompressor.java
- src/main/java/jp/co/yahoo/yosegi/compressor/BZip2CommonsCompressor.java
- src/main/java/jp/co/yahoo/yosegi/compressor/CompressorNameShortCut.java
- src/main/java/jp/co/yahoo/yosegi/compressor/DeflateCommonsCompressor.java
- src/main/java/jp/co/yahoo/yosegi/compressor/FramedLZ4CommonsCompressor.java
- src/main/java/jp/co/yahoo/yosegi/compressor/GzipCommonsCompressor.java
- src/main/java/jp/co/yahoo/yosegi/compressor/LzmaCommonsCompressor.java
- src/main/java/jp/co/yahoo/yosegi/compressor/SnappyCommonsCompressor.java
- src/main/java/jp/co/yahoo/yosegi/compressor/ZstdCommonsCompressor.java
- src/test/java/jp/co/yahoo/yosegi/compressor/TestCompressor.java
If the data size is large, it will be 0 bytes in the Framed class.
Although the data size is required when creating OutputStream, the class has been changed because decoding was confirmed even with large data size.
I reproduced the data size in 2MB but failed in LZ4.
Implementation of unit test is implemented by ISSUE of LZ4.
https://yosegi.atlassian.net/browse/YOSEGI-66
> Yosegi-65 It becomes an array of NULL when decoding Snappy.

- src/test/java/jp/co/yahoo/yosegi/blackbox/TestGetPrimitiveObjectArray.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestMultiArray.java
Unit tests fail for encodings that do not support row filters.
Removed test cases that are predicated on being filtered.
> Yosegi-78 Removed premise tests where row-by-line filters are applied.

- pom.xml
- src/main/java/jp/co/yahoo/yosegi/spread/column/UnionColumn.java
- src/test/java/jp/co/yahoo/yosegi/spread/column/TestUnionColumn.java
Changed code to call setPrimitiveObject internally.
I created a unit test and confirmed that this method works properly.
> Yosegi-88 setPrimitiveObject () is not implemented in UnionColumn

- pom.xml
- src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpSpreadColumnBinaryMaker.java
- src/main/java/jp/co/yahoo/yosegi/inmemory/IMemoryAllocator.java
The query engine defines a specific column in Row Type.
When there is a column that is not defined in Row Type in the file, I want to skip load process.
However, there is no interface to notify that the load process is unnecessary.
Add an interface to skip unnecessary load on Row Type on Yosegi side.
The existing unit tests have passed.
The default handling of the interface does not allow skipping.
> Yosegi-89 Addition of interface to skip load processing

- pom.xml
- src/main/java/jp/co/yahoo/yosegi/binary/maker/BufferDirectDictionaryLinkCellManager.java
- src/main/java/jp/co/yahoo/yosegi/binary/maker/ConstantColumnBinaryMaker.java
There is a bug that gives incorrect results when the column and the total number of rows do not match in the NULL filter.
Since the current filter cannot get the total number of rows, I fixed it by removing the processing of NULL filter.
> Bug fix on NULL filter.

- pom.xml
- src/main/java/jp/co/yahoo/yosegi/spread/column/IColumn.java
- src/main/java/jp/co/yahoo/yosegi/spread/expand/ExpandColumn.java
When extracting data from expanded columns, a large amount of memory may be copied if the length of array is large.
It is desirable to have an interface that returns the Expand column test and internal columns to avoid memory copying.
> Yosegi-93 Determine if expanded column.

- pom.xml
- src/test/java/jp/co/yahoo/yosegi/util/TestIndexAndObject.java
Upgrade jacoco from 0.8.0 to 0.8.6 (the latest version as of now).
https://www.jacoco.org/jacoco/trunk/doc/changes.html
JIRA: https://yosegi.atlassian.net/browse/YOSEGI-94
I ran "mvn test" with AdoptOpenJDK 11.0.9.
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestIndexAndObject.T_addAndGet_throwsExeption_withSmallerThanStartIndex:92 Unexpected exception type thrown ==> expected: <java.lang.ArrayIndexOutOfBoundsException> but was: <java.lang.IndexOutOfBoundsException>
[INFO] 
[ERROR] Tests run: 8532, Failures: 1, Errors: 0, Skipped: 0
```
The above failure can be fixed in a separate issue.
> Yosegi-94 Upgrade jacoco to 0.8.6 to support JDK 11

- src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinaryMakerConfig.java
- src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinaryMakerNameShortCut.java
- src/main/java/jp/co/yahoo/yosegi/binary/maker/FlagIndexedOptimizedNullArrayDumpBooleanColumnBinaryMaker.java
- src/main/java/jp/co/yahoo/yosegi/binary/maker/index/FlagBooleanIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/BlockIndexNameShortCut.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/BlockIndexNode.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/BlockIndexType.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/BooleanBlockIndex.java
- src/main/java/jp/co/yahoo/yosegi/blockindex/EncryptionSupportedBlockIndexNode.java
- src/test/java/jp/co/yahoo/yosegi/binary/TestColumnBinaryMakerConfig.java
- src/test/java/jp/co/yahoo/yosegi/binary/maker/TestFlagIndexedOptimizedNullArrayDumpBooleanColumnBinaryMaker.java
- src/test/java/jp/co/yahoo/yosegi/binary/maker/index/TestFlagBooleanIndex.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanBlockIndex.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanCellIndex.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanPrimitiveColumn.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeBoolean.java
- src/test/java/jp/co/yahoo/yosegi/blockindex/TestBlockIndexNameShortCut.java
- src/test/java/jp/co/yahoo/yosegi/blockindex/TestBooleanBlockIndex.java
- src/test/resources/blackbox/TestBooleanBlockIndex.json
I would like to add the BooleanBlockIndex for filtering boolean columns.
I added two indexes and a new ColumnBinaryMaker below for the boolean filter.
1. index
* jp.co.yahoo.yosegi.blockindex.BooleanBlockIndex
* jp.co.yahoo.yosegi.binary.maker.index.FlagBooleanIndex
1. ColumnBinaryMaker
* jp.co.yahoo.yosegi.binary.maker.FlagIndexedOptimizedNullArrayDumpBooleanColumnBinaryMaker
I modified sources related to the boolean filter.
* Changed the booleanMakerClass in ColumnBinaryMakerConfig to FlagIndexed...ColumnBinaryMaker.
* Added FlagIndexed...ColumnBinaryMaker to ColumnBinaryMakerNameShortCut.
* Added BOOLEAN to BlockIndexType.
* Added BooleanBlockIndex to BlockIndexNameShortCut(RangeBlockIndexNameShortCut)
I refactored sources for adding a BlockIndexNameShortCut.
* Renamed …
> Add BooleanBlockIndex

- src/main/java/jp/co/yahoo/yosegi/reader/YosegiSchemaReader.java
- src/test/java/jp/co/yahoo/yosegi/binary/TestColumnBinaryTree.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanBlockIndex.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestEmptyArray.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestExpandAndFlatten.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestMultiArray.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestPrimitiveSchema.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestUnionSchema.java
- src/test/java/jp/co/yahoo/yosegi/spread/flatten/TestFlatten.java
Deprecate YosegiReader.next method.
Replace YosegiReader into WrapReader in unit tests.
> Deprecate YosegiReader.next method

- src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinary.java
- src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinaryUtil.java
- src/main/java/jp/co/yahoo/yosegi/binary/RepetitionAndLoadSize.java
- src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayStringColumnBinaryMaker.java
- src/main/java/jp/co/yahoo/yosegi/block/EncryptionSupportedBlockReader.java
- src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockReader.java
- src/main/java/jp/co/yahoo/yosegi/reader/WrapReader.java
- src/main/java/jp/co/yahoo/yosegi/spread/expand/ExpandFunction.java
- src/main/java/jp/co/yahoo/yosegi/spread/expand/ExpandNode.java
- src/main/java/jp/co/yahoo/yosegi/spread/expand/IExpandFunction.java
- src/main/java/jp/co/yahoo/yosegi/spread/expand/LinkColumn.java
- src/test/java/jp/co/yahoo/yosegi/blackbox/TestStringPrimitiveColumn.java
- src/test/java/jp/co/yahoo/yosegi/spread/expand/TestExpandNode.java
Change the return value of expand from index to number of iterations.
I haven't deleted loadIndex right now. It will be removed when all ColumnBinaryMakers are no longer in use.
I rewrote the unit test.
> Change the return value of expand from index to number of iterations.

- pom.xml
Hi, @koijima , @yohto , I'd like to report a vulnerability issue in **jp.co.yahoo.yosegi:yosegi:2.0.1**.
I noticed that **jp.co.yahoo.yosegi:yosegi:2.0.1** directly depends on **com.github.luben:zstd-jni:v1.3.3-3**. However ,as shown in the following dependency graph. **com.github.luben:zstd-jni:v1.3.3-3** sufferes from the vulnerability which the C library **zstd(version:1.3.3)** exposed: [CVE-2021-24031](https://nvd.nist.gov/vuln/detail/CVE-2021-24031),[CVE-2019-11922](https://nvd.nist.gov/vuln/detail/CVE-2019-11922).
**com.github.luben:zstd-jni:v1.4.9-1** (**>=v1.4.9-1**) has upgraded this vulnerable C library `zstd` to the patch version **1.4.9**.
Java build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Java projects. Could …
> Potential security vulnerability in the zstd C library.
