README.md

[YOSEGI-7] There is no JIRA link in the README.

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpBooleanColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanPrimitiveColumn.java

Fixed a bug that access to invalid array.
If Spread is longer, it accesses a value larger than the buffer.
I first made a unit test and confirmed that an Exception will be given.

[YOSEGI-9] Boolean type and an exception occurs during filter operation.

---

CONTRIBUTING.md
README.md

I created a contribution guide.
Create CONTRIBUTING.md.

[Yosegi-2] Create CONTRIBUTING.md

---

src/main/java/jp/co/yahoo/yosegi/compressor/GzipCompressor.java
src/test/java/jp/co/yahoo/yosegi/compressor/TestGzipCompressor.java

I implemented the compression level control function in gzip compression class.
https://yosegi.atlassian.net/browse/YOSEGI-10
I created a unit test and checked whether the compression level setting is less than the minimum value.

[Yosegi-20] Implement compression level optimization on gzip.

---

src/main/java/jp/co/yahoo/yosegi/compressor/DeflateCommonsCompressor.java
src/test/java/jp/co/yahoo/yosegi/compressor/TestDeflateCommonsCompressor.java

I implemented the compression level control function in deflate compression class.
I created a unit test and checked whether the compression level setting is less than the minimum value.

[Yosegi-22]Implement compression level optimization on deflate.

---

src/main/java/jp/co/yahoo/yosegi/reader/YosegiArrowReader.java
src/main/java/jp/co/yahoo/yosegi/spread/ArrowSpreadUtil.java
src/main/java/jp/co/yahoo/yosegi/spread/column/ArrowColumnFactory.java
src/main/java/jp/co/yahoo/yosegi/writer/YosegiArrowWriter.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestArrowConvert.java

Python is a common language for data processing.
I want to write and read Yosegi files with python.
This PR is an additional function to read and write from Arrow's byte array.

[Yosegi-24] Read and write Yosegi files with pyarrow.

---

src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonArrayFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonBaseFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonObjectFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextBooleanFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextMapFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextNumericalFormatterFactory.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextStringFormatter.java
src/main/java/jp/co/yahoo/yosegi/util/CascadingDispatcherFactory.java

refactoring code using functional map
path through default maven test

refactoring

---

src/main/java/jp/co/yahoo/yosegi/message/design/ArrayContainerField.java
src/main/java/jp/co/yahoo/yosegi/message/design/BooleanField.java
src/main/java/jp/co/yahoo/yosegi/message/design/ByteField.java
src/main/java/jp/co/yahoo/yosegi/message/design/BytesField.java
src/main/java/jp/co/yahoo/yosegi/message/design/DoubleField.java
src/main/java/jp/co/yahoo/yosegi/message/design/FloatField.java
src/main/java/jp/co/yahoo/yosegi/message/design/IField.java
src/main/java/jp/co/yahoo/yosegi/message/design/IntegerField.java
src/main/java/jp/co/yahoo/yosegi/message/design/LongField.java
src/main/java/jp/co/yahoo/yosegi/message/design/MapContainerField.java
src/main/java/jp/co/yahoo/yosegi/message/design/NullField.java
src/main/java/jp/co/yahoo/yosegi/message/design/Properties.java
src/main/java/jp/co/yahoo/yosegi/message/design/ShortField.java
src/main/java/jp/co/yahoo/yosegi/message/design/SimpleField.java
src/main/java/jp/co/yahoo/yosegi/message/design/StringField.java
src/main/java/jp/co/yahoo/yosegi/message/design/StructContainerField.java
src/main/java/jp/co/yahoo/yosegi/message/design/UnionField.java
src/main/java/jp/co/yahoo/yosegi/message/design/java/JavaObjectToField.java

refactoring code for readable
path through default maven test

refactoring jp.co.yahoo.yosegi.message.design

---

src/main/java/jp/co/yahoo/yosegi/block/Block.java
src/main/java/jp/co/yahoo/yosegi/block/ColumnBinaryTree.java
src/main/java/jp/co/yahoo/yosegi/block/ColumnNameNode.java
src/main/java/jp/co/yahoo/yosegi/block/FindBlockWriter.java
src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockReader.java
src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockWriter.java
src/main/java/jp/co/yahoo/yosegi/block/ReadColumnUtil.java

refactoring
Path through maven test

refactoring jp.co.yahoo.yosegi.block

---

src/main/java/jp/co/yahoo/yosegi/util/ByteArrayData.java
src/main/java/jp/co/yahoo/yosegi/util/ByteLineReader.java
src/main/java/jp/co/yahoo/yosegi/util/FindClass.java
src/main/java/jp/co/yahoo/yosegi/util/NumberUtils.java

refactoring including lazy evaluation 
Path through maven test

refactoring jp.co.yahoo.yosegi.util

---

src/main/java/jp/co/yahoo/yosegi/compressor/BZip2CommonsCompressor.java
src/main/java/jp/co/yahoo/yosegi/compressor/CompressorNameShortCut.java
src/main/java/jp/co/yahoo/yosegi/compressor/DeflateCommonsCompressor.java
src/main/java/jp/co/yahoo/yosegi/compressor/GzipCommonsCompressor.java
src/main/java/jp/co/yahoo/yosegi/compressor/GzipCompressor.java

use map dispatcher instead of switch
Path through maven test

refactoring jp.co.yahoo.yosegi.compressor

---

src/main/java/jp/co/yahoo/yosegi/message/parser/PrimitiveConverter.java
src/main/java/jp/co/yahoo/yosegi/message/parser/java/JavaListParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/java/JavaMapParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/java/JavaParserFactory.java
src/main/java/jp/co/yahoo/yosegi/message/parser/json/JacksonArrayParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/json/JacksonObjectParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextArrayParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextMapParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextMessageReader.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextPrimitiveConverter.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextStructParser.java

refactoring including change switch to map dispatch
Path throw maven test

refactoring jp.co.yahoo.yosegi.message.parser

---

src/main/java/jp/co/yahoo/yosegi/reader/DirectArrowLoader.java
src/main/java/jp/co/yahoo/yosegi/reader/DynamicArrowLoader.java
src/main/java/jp/co/yahoo/yosegi/reader/DynamicSchemaRootMemoryAllocator.java
src/main/java/jp/co/yahoo/yosegi/reader/InMemoryStorageLoader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiArrayParser.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiArrowReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiParserFactory.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiSchemaReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiSchemaSpreadReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiSpreadParser.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiStatsReader.java

refactoring including switch to map dispatch
Path through maven test

refactoring jp.co.yahoo.yosegi.reader

---

src/main/java/jp/co/yahoo/yosegi/blockindex/RangeBlockIndexName.java
src/main/java/jp/co/yahoo/yosegi/blockindex/RangeBlockIndexNameShortCut.java
src/main/java/jp/co/yahoo/yosegi/compressor/CompressorName.java
src/main/java/jp/co/yahoo/yosegi/util/INamePair.java
src/main/java/jp/co/yahoo/yosegi/util/NamePair.java

use NamePair structure instead of Pair directly.
path through maven test

add NamePair class

---

src/main/java/jp/co/yahoo/yosegi/blockindex/BlockIndexNode.java
src/main/java/jp/co/yahoo/yosegi/blockindex/ByteRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/DoubleRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/FindBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/FloatRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/FullRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/IntegerRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/LongRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/RangeBlockIndexNameShortCut.java
src/main/java/jp/co/yahoo/yosegi/blockindex/ShortRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/StringRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/util/NumberUtils.java

refactoring switch struct to map dispatcher
path trough the maven test

refactoring jp.co.yahoo.yosegi.blockindex

---

pom.xml

version up for deploy to Maven Repository
deployed to Maven Repository

version up for deploy to Maven Repository

---

src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonArrayFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonBaseFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonObjectFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextBooleanFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextBytesFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextFormatterFactory.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextStringFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/objects/JavaObjectToPrimitiveObject.java
src/main/java/jp/co/yahoo/yosegi/message/objects/JsonNodeToPrimitiveObject.java
src/main/java/jp/co/yahoo/yosegi/message/objects/ObjectToJsonNode.java
src/main/java/jp/co/yahoo/yosegi/message/parser/json/JsonNodeToParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextParserFactory.java

Revert "Patch/revert if else if class cascade"

---

pom.xml

Revert "version up for deploy to Maven Repository"

---

src/main/java/jp/co/yahoo/yosegi/blockindex/BlockIndexNode.java
src/main/java/jp/co/yahoo/yosegi/blockindex/ByteRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/DoubleRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/FindBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/FloatRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/FullRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/IntegerRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/LongRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/RangeBlockIndexNameShortCut.java
src/main/java/jp/co/yahoo/yosegi/blockindex/ShortRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/StringRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/util/NumberUtils.java

Revert "refactoring jp.co.yahoo.yosegi.blockindex"

---

src/main/java/jp/co/yahoo/yosegi/reader/DirectArrowLoader.java
src/main/java/jp/co/yahoo/yosegi/reader/DynamicArrowLoader.java
src/main/java/jp/co/yahoo/yosegi/reader/DynamicSchemaRootMemoryAllocator.java
src/main/java/jp/co/yahoo/yosegi/reader/InMemoryStorageLoader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiArrayParser.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiArrowReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiParserFactory.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiSchemaReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiSchemaSpreadReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiSpreadParser.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiStatsReader.java

Revert "refactoring jp.co.yahoo.yosegi.reader"

---

src/main/java/jp/co/yahoo/yosegi/message/objects/BooleanObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/ByteObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/DoubleObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/FloatObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/IntegerObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/LongObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/PrimitiveObjectContainer.java
src/main/java/jp/co/yahoo/yosegi/message/objects/PrimitiveObjectMaker.java
src/main/java/jp/co/yahoo/yosegi/message/objects/PrimitiveObjectToJsonNode.java
src/main/java/jp/co/yahoo/yosegi/message/objects/ShortObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/StringObj.java

Revert "refactoring of jp.co.yahoo.yosegi.message.objects"

---

src/main/java/jp/co/yahoo/yosegi/message/parser/PrimitiveConverter.java
src/main/java/jp/co/yahoo/yosegi/message/parser/java/JavaListParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/java/JavaMapParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/json/JacksonArrayParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/json/JacksonObjectParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextArrayParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextMapParser.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextMessageReader.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextPrimitiveConverter.java
src/main/java/jp/co/yahoo/yosegi/message/parser/text/TextStructParser.java

Revert "refactoring jp.co.yahoo.yosegi.message.parser"

---

src/main/java/jp/co/yahoo/yosegi/compressor/BZip2CommonsCompressor.java
src/main/java/jp/co/yahoo/yosegi/compressor/CompressorNameShortCut.java
src/main/java/jp/co/yahoo/yosegi/compressor/DeflateCommonsCompressor.java
src/main/java/jp/co/yahoo/yosegi/compressor/GzipCommonsCompressor.java
src/main/java/jp/co/yahoo/yosegi/compressor/GzipCompressor.java

Revert "refactoring jp.co.yahoo.yosegi.compressor"

---

src/main/java/jp/co/yahoo/yosegi/util/ByteArrayData.java
src/main/java/jp/co/yahoo/yosegi/util/ByteLineReader.java
src/main/java/jp/co/yahoo/yosegi/util/FindClass.java
src/main/java/jp/co/yahoo/yosegi/util/NumberUtils.java

Revert "refactoring jp.co.yahoo.yosegi.util"

---

src/main/java/jp/co/yahoo/yosegi/block/Block.java
src/main/java/jp/co/yahoo/yosegi/block/ColumnBinaryTree.java
src/main/java/jp/co/yahoo/yosegi/block/ColumnNameNode.java
src/main/java/jp/co/yahoo/yosegi/block/FindBlockWriter.java
src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockReader.java
src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockWriter.java
src/main/java/jp/co/yahoo/yosegi/block/ReadColumnUtil.java

Revert "refactoring jp.co.yahoo.yosegi.block"

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpArrayColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpBytesColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/UnsafeOptimizeLongColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeBoolean.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeByte.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeBytes.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeDouble.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeFloat.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeInteger.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeLong.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeShort.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeString.java

Fixed a bug in the calculation process.

Yosegi-38 Create Test Case of Logical Data Size.

---

pom.xml

version up for deploying to maven repository.
Deployed to maven repository

version up

---

pom.xml

To upload to maven repository.
It can be uploaded to maven repository

version up to upload to maven repository

---

pom.xml

version up to maven repository.
Changing from previous version is too small, then I up branch version of it.
Upload to maven repository

version up to maven repository

---

pom.xml

Upgraded for security alert.
The version has been upgraded, but there is no problem with compilation and unit testing.

[Yosegi-46] jackson and jetty security alerts.

---

src/main/java/jp/co/yahoo/yosegi/reader/YosegiReader.java
src/main/java/jp/co/yahoo/yosegi/writer/YosegiWriter.java
src/test/java/jp/co/yahoo/yosegi/block/TestPushdownSupportedBlockReader.java
src/test/java/jp/co/yahoo/yosegi/reader/TestYosegiReader.java

Fixed a bug that hasNext becomes true when next does not exist in Pushdown processing.
An exception occurred in a unit test. Then I fixed the code.

[Yosegi-49]NullPonterException occurs in Pushdown processing.

---

pom.xml

Version up to upload maven repository.
uploaded to maven repository

version up to upload maven repository

---

docs/code_conventions.md
docs/developing.md

Describe how to create test class and its methods.
Discussed with other contributor about how to create tests.

add code converntions

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/BufferDirectCellManager.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/BufferDirectDictionaryLinkCellManager.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/ConstantColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpArrayColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpBooleanColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/spread/column/CellMakerFactory.java
src/main/java/jp/co/yahoo/yosegi/spread/column/IArrowPrimitiveConnector.java
src/main/java/jp/co/yahoo/yosegi/spread/column/ICellMaker.java
src/main/java/jp/co/yahoo/yosegi/spread/column/ICellManager.java
src/main/java/jp/co/yahoo/yosegi/spread/column/PrimitiveCellManager.java
src/main/java/jp/co/yahoo/yosegi/spread/column/PrimitiveColumn.java
src/main/java/jp/co/yahoo/yosegi/util/IndexAndObject.java
src/main/java/jp/co/yahoo/yosegi/util/RangeBinarySearch.java
src/test/java/jp/co/yahoo/yosegi/spread/column/TestCellMakerFactory.java
src/test/java/jp/co/yahoo/yosegi/spread/column/TestPrimitiveCellManager.java
src/test/java/jp/co/yahoo/yosegi/util/TestIndexAndObject.java
src/test/java/jp/co/yahoo/yosegi/util/TestRangeBinarySearch.java

A large amount of memory required for write processing.
In the current code, an instance of Cell consumes Heap.
```
1:        308131       11870736  [C
2:        526893        8430288  jp.co.yahoo.yosegi.message.objects.IntegerObj
3:        526893        8430288  jp.co.yahoo.yosegi.spread.column.IntegerCell
4:        308109        7394616  java.lang.String
5:        457938        7327008  jp.co.yahoo.yosegi.spread.column.StringCell
6:        434261        6948176  jp.co.yahoo.yosegi.message.objects.StringObj
7:         20947        6861712  [Ljava.lang.Object;
8:          5632        5431032  [B
9:         64791        1554984  java.lang.Double
10:         69871        1117936  java.lang.Integer
```
Create instance at requested timing without caching Cell instance.
This reduces the heap …

Yosegi-45 The heap size of PrimitiveCell is large in write processing.

---

src/test/java/jp/co/yahoo/yosegi/message/design/TestBooleanField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestByteField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestBytesField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestDoubleField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestFloatField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestIntegerField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestLongField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestMapContainerField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestNullField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestProperties.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestShortField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestStringField.java
src/test/java/jp/co/yahoo/yosegi/message/design/TestUnionField.java

Yosegi-47 Add a unit test to the message.design.

---

src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonMessageWriter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/json/JacksonParserToJsonObject.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/json/TestJacksonArrayFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/json/TestJacksonContainerToJsonObject.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/json/TestJacksonMessageWriter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/json/TestJacksonObjectFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/json/TestJacksonParserToJsonObject.java

Added a unit test.
And fix bugs that don't pass unit tests

Yosegi-48 Add a unit test to the message.formatter.json.

---

src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockWriter.java
src/test/java/jp/co/yahoo/yosegi/block/TestPushdownSupportedBlockWriter.java

The binary size of the block index was not calculated by canAppend ().
Added test case to compare size after append.

Yosegi-57 Buffer overflow.

---

pom.xml

version up for uploading to maven repository
it has been uploaded

version up for uploading to maven repository

---

pom.xml

Version up for upload to Maven repository.

version up for upload to maven repository

---

src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinaryMakerNameShortCut.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/MaxLengthBasedArrayColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/binary/maker/TestMaxLengthBasedArrayColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestNullCellIndex.java

The current Maker of Array has a large data size when converting the size numbers to binary.
I created a class that uses a type with the smallest size of array.
However, since this is not the default, this class is not used unless it is explicitly set.

Yosegi-61 Create BinaryMaker with reduced byte size of Array encoding.

---

src/main/java/jp/co/yahoo/yosegi/message/objects/BytesObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/DoubleObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/FloatObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/StringObj.java
src/main/java/jp/co/yahoo/yosegi/message/objects/Utf8BytesLinkObj.java
src/test/java/jp/co/yahoo/yosegi/binary/maker/index/TestBufferDirectSequentialNumberCellIndexFloat.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestBooleanObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestByteObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestBytesObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestBytesStringObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestDoubleObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestFloatObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestIntegerObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestJavaObjectToPrimitiveObject.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestJsonNodeToPrimitiveObject.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestLongObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestNullObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestPrimitiveObjectToJsonNode.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestShortObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestStringObj.java
src/test/java/jp/co/yahoo/yosegi/message/objects/TestUtf8BytesLinkObj.java

Added a unit test.
And fix bugs that don't pass unit tests

Yosegi-58 Add a unit test to the message.objects

---

src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextArrayFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextBooleanFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextBytesFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextDoubleFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextFloatFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextIntegerFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextLongFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextShortFormatter.java
src/main/java/jp/co/yahoo/yosegi/message/formatter/text/TextStringFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextArrayFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextBooleanFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextBytesFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextDoubleFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextFloatFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextFormatterFactory.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextIntegerFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextLongFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextMapFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextNullFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextShortFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextStreamWriter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextStringFormatter.java
src/test/java/jp/co/yahoo/yosegi/message/formatter/text/TestTextStructFormatter.java

Added a unit test.
And fix bugs that don't pass unit tests

Yosegi-48 Add a unit test to the message.formatter.text.

---

pom.xml

version up to deploy to Maven Repository

version up to deploy to Maven Repository

---

pom.xml
src/main/java/jp/co/yahoo/yosegi/compressor/CompressorNameShortCut.java
src/main/java/jp/co/yahoo/yosegi/compressor/SnappyCompressor.java
src/test/java/jp/co/yahoo/yosegi/compressor/TestCompressor.java

Added Snappy.
This class performs common unit tests.

Yosegi-65 It becomes an array of NULL when decoding Snappy.

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/DictionaryRleStringColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayStringColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/RleStringColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/compressor/TestCompressor.java

Yosegi-63 update is incomplete and fails to compile.
Also, the test does not pass due to a bug in LZ4. Since the bug has already been reported, we will comment out this ticket so that it can be compiled.
https://yosegi.atlassian.net/browse/YOSEGI-66

Yosegi-67 Bugfix. Cannot compile.

---

pom.xml

Updated jackson for security alerts.

Yosegi-68 Updated jackson for security alerts.

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestBytePrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestIntegerPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestLongPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestShortPrimitiveColumn.java

Added a case to verify encoding and decoding for each range.
This is because there are more and more encoding implementations that store numerically the minimum necessary bytes.

Yosegi-69 Added numeric generic test cases.

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayCellManager.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanPrimitiveColumn.java

The Boolean generic test does not include OptimizedNullArrayDumpBooleanColumnBinary.
Added unit tests and bug fixes.

Yosegi-70 New class added to Boolean generic test.

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestBytesPrimitiveColumn.java

There is no binary generic unit test.
Create a generic test just like any other type.

Yosegi-72 Create generic unit tests for binary encoding.

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestDoublePrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestFloatPrimitiveColumn.java

New encoding class added to Float and Double generic tests.

Yosegi-73 New classes added to Float and Double generic tests.

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeBoolean.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeByte.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeBytes.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeDouble.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeFloat.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestCalcLogicalDataSizeLong.java

A new encoding class was added.

Yosegi-74 New class added to generic test to check logical data size.

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanCellIndex.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestNullCellIndex.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestNumberBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestNumberCellIndex.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestStringBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestStringCellIndex.java

A new encoding class was added.

Yosegi-75 New class added to filter generic test.

---

src/main/java/jp/co/yahoo/yosegi/util/io/rle/RleConverter.java
src/test/java/jp/co/yahoo/yosegi/util/io/rle/TestRleConverter.java

Created unit tests for RLE utilities.
A small bug was also fixed.

Yosegi-76 Create RLE utility class test.

---

src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/ByteNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/DiffLongNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/FixedNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/INumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/IntegerNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/LongNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/ShortNumEncoder.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/EncoderTestDictionary.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/EncoderTestMemoryAllocator.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/TestByteNumEncoder.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/TestDiffLongNumEncoder.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/TestFixedNumEncoder.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/TestIntegerNumEncoder.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/TestLongNumEncoder.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/TestNumEncoderUtil.java
src/test/java/jp/co/yahoo/yosegi/util/io/diffencoder/TestShortNumEncoder.java

Created unit tests.
Also fixed bugs.

Yosegi-77 Creating unit tests for jp.co.yahoo.yosegi.util.io.diffencoder.

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayStringColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestStringPrimitiveColumn.java

Data is corrupted due to an encoding bug.
The code was fixed because the last index of Not null has not been updated.
I have created a unit test that reproduces this bug and confirmed that it passes.

Yosegi-81 The value is in a row that is null.

---

pom.xml

Yosegi-80 Update common compress for security alerts.

---

pom.xml
src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinary.java
src/main/java/jp/co/yahoo/yosegi/binary/ColumnBinaryMakerConfig.java
src/main/java/jp/co/yahoo/yosegi/block/EncryptionSupportedBlockReadOffset.java
src/main/java/jp/co/yahoo/yosegi/block/EncryptionSupportedBlockReader.java
src/main/java/jp/co/yahoo/yosegi/block/IBlockReader.java
src/main/java/jp/co/yahoo/yosegi/block/PushdownSupportedBlockReader.java
src/main/java/jp/co/yahoo/yosegi/message/design/StructContainerField.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiReader.java

Presto has a function to measure memory usage and adjust the amount of memory for tasks.
In order to use this function effectively, it is necessary to have a function to get the amount of bytes allocated from the reader.

Yosegi-87 Added the function to get the amount of bytes read

---

pom.xml
src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayStringColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/block/BlockReaderNameShortCut.java
src/test/java/jp/co/yahoo/yosegi/binary/maker/TestOptimizedNullArrayStringColumnBinaryMaker.java

The count written during conversion was incorrect.
This corrupted the byte array and caused a bug where the original number could not be restored.
I created a unit test and confirmed that it passed after the code was modified.

Fixed a fatal data corruption bug.

---

pom.xml
src/main/java/jp/co/yahoo/yosegi/binary/maker/index/BufferDirectSequentialStringCellIndex.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/index/SequentialStringCellIndex.java

This is a fatal bug that the lines that should be output are filtered because the filter does not work properly.

Fixed a bug that the operation of the character string with the line feed code is wrong.

---

pom.xml

I need a test coverage report to refactor.Therefore, update it so that a report is output after the test is executed.

Yosegi-90 Output test coverage report.

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/DictionaryRleStringColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpArrayColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpUnionColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiArrowReader.java
src/main/java/jp/co/yahoo/yosegi/reader/YosegiStatsReader.java
src/main/java/jp/co/yahoo/yosegi/spread/analyzer/ByteColumnAnalizer.java
src/main/java/jp/co/yahoo/yosegi/spread/expand/ExpandSpread.java

Removed some warnings output by analysis tools.

minor refactoring

---

pom.xml
src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayCellManager.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDicCellManager.java
src/main/java/jp/co/yahoo/yosegi/spread/flatten/FlattenFunction.java
src/main/java/jp/co/yahoo/yosegi/spread/flatten/FlattenFunctionFactory.java
src/main/java/jp/co/yahoo/yosegi/util/replacement/DefaultReplacement.java
src/main/java/jp/co/yahoo/yosegi/util/replacement/IPrefix.java
src/main/java/jp/co/yahoo/yosegi/util/replacement/IReplacement.java
src/main/java/jp/co/yahoo/yosegi/util/replacement/LowerReplacement.java
src/main/java/jp/co/yahoo/yosegi/util/replacement/PrefixAndSuffix.java
src/main/java/jp/co/yahoo/yosegi/util/replacement/ReplacementFactory.java
src/test/java/jp/co/yahoo/yosegi/binary/maker/TestOptimizedNullArrayDicCellManager.java
src/test/java/jp/co/yahoo/yosegi/spread/flatten/TestFlatten.java
src/test/java/jp/co/yahoo/yosegi/util/replacement/TestPrefixAndSuffix.java
src/test/java/jp/co/yahoo/yosegi/util/replacement/TestReplacementFactory.java

Added the ability to set Flatten with a shorter description.
There is no need to change the description due to version upgrade because it is backward compatible.
Added unit test. It has passed the tests so far.

Yosegi-91 Shorten the setting string of Flatten.

---

pom.xml
src/main/java/jp/co/yahoo/yosegi/blockindex/ByteRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/DoubleRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/FloatRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/IntegerRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/LongRangeBlockIndex.java
src/main/java/jp/co/yahoo/yosegi/blockindex/ShortRangeBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blockindex/TestByteRangeBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blockindex/TestDoubleRangeBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blockindex/TestFloatRangeBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blockindex/TestIntegerRangeBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blockindex/TestLongRangeBlockIndex.java
src/test/java/jp/co/yahoo/yosegi/blockindex/TestShortRangeBlockIndex.java

It was fixed because the processing of the filter was wrong.
I created a unit test and confirmed that the result is correct.

Yosegi-92 Range filter results incorrect.

---

pom.xml
src/main/java/jp/co/yahoo/yosegi/compressor/GzipCompressor.java

Fixed a bug in gzip's decompress that didn't close InputStream.

Fixed a bug in gzip's decompress that didn't close InputStream.

---

.circleci/.maven.xml
.circleci/config.yml
pom.xml

I changed circleci/config.yml for using sonatype-nexus-community/circleci-maven-release-orb to deploy to the maven central automatically.
I have to check it on the circleci by this pullrequest.

Change circleci/config.yml

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanBlockIndex.java

I fixed blackbox/TestBooleanBlockIndex, because Pair class doesn't exist in JavaSE8.
I fixed blackbox/TestBooleanBlockIndex.

Fix blackbox/TestBooleanBlockIndex

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/ConstantColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpSpreadColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/IColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/MaxLengthBasedArrayColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpStringColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayStringColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/RleStringColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/binary/maker/UnsupportedColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/inmemory/ArrowArrayLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/ArrowLoaderFactoryUtil.java
src/main/java/jp/co/yahoo/yosegi/inmemory/ArrowMapLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/ArrowStructLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/IArrayLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/IConstLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/ILoaderFactory.java
src/main/java/jp/co/yahoo/yosegi/inmemory/ISpreadLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/LoadType.java
src/main/java/jp/co/yahoo/yosegi/inmemory/YosegiArrayLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/YosegiConstLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/YosegiLoaderFactory.java
src/main/java/jp/co/yahoo/yosegi/inmemory/YosegiSpreadLoader.java
src/test/java/jp/co/yahoo/yosegi/binary/maker/TestConstantColumnBinaryMaker.java

Added a constant type loader.

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpDoubleColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestDoublePrimitiveColumn.java

Add a load method to OptimizedNullArrayDumpDoubleColumnBinaryMaker
In TestDoublePrimitiveColumn

Add a load method to OptimizedNullArrayDumpDoubleColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpDoubleColumnBinaryMaker.java

Modified the getLoadType method to match the interface.
Tested in TestDoublePrimitiveColumn.

Mod the getLoadType method of OptimizedNullArrayDumpDoubleColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpFloatColumnBinaryMaker.java

Add a load method to OptimizedNullArrayDumpFloatColumnBinaryMaker.

Add a load method to OptimizedNullArrayDumpFloatColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayFloatColumnBinaryMaker.java

Add a load method to OptimizedNullArrayFloatColumnBinaryMaker.

Add a load method to OptimizedNullArrayFloatColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/DumpUnionColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/inmemory/ArrowUnionLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/IUnionLoader.java
src/main/java/jp/co/yahoo/yosegi/inmemory/YosegiLoaderFactory.java
src/main/java/jp/co/yahoo/yosegi/inmemory/YosegiUnionLoader.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestUnionColumn.java

Added a union type loader.

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpFloatColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestFloatPrimitiveColumn.java

Add loadFromExpandColumnBinary method to OptimizedNullArrayDumpFloatColumnBinaryMaker

Add loadFromExpandColumnBinary method to OptimizedNullArrayDumpFloatColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayFloatColumnBinaryMaker.java

Add loadFromExpandColumnBinary method to OptimizedNullArrayFloatColumnBinaryMaker

Add loadFromExpandColumnBinary method to OptimizedNullArrayFloatColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDoubleColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestDoublePrimitiveColumn.java

Add a load method to OptimizedNullArrayDoubleColumnBinaryMaker.
In TestDoublePrimitiveColumn.

Add a load method to OptimizedNullArrayDoubleColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpBooleanColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanPrimitiveColumn.java

Add a load method to OptimizedNullArrayDumpBooleanColumnBinaryMaker.
In TestBooleanPrimitiveColumn.

Add a load method to OptimizedNullArrayDumpBooleanColumnBinaryMaker

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestFloatPrimitiveColumn.java

Add OptimizedNullArrayFloatColumnBinaryMaker to TestFloatPrimitiveColumn.

Add OptimizedNullArrayFloatColumnBinaryMaker to TestFloatPrimitiveColumn

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/FlagIndexedOptimizedNullArrayDumpBooleanColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanPrimitiveColumn.java

Add a load method to FlagIndexedOptimizedNullArrayDumpBooleanColumnBinaryMaker.
In TestBooleanPrimitiveColumn.

Add a load method to FlagIndexedOptimizedNullArrayDumpBooleanColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpBytesColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestBytesPrimitiveColumn.java

Add a load method to OptimizedNullArrayDumpBytesColumnBinaryMaker.
In TestBytesPrimitiveColumn.

Add a load method to OptimizedNullArrayDumpBytesColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpLongColumnBinaryMaker.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/ByteNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/DiffLongNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/FixedNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/INumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/IntegerNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/LongNumEncoder.java
src/main/java/jp/co/yahoo/yosegi/util/io/diffencoder/ShortNumEncoder.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestLongPrimitiveColumn.java

Add a load method to OptimizedNullArrayDumpLongColumnBinaryMaker
In TestLongPrimitiveColumn.

Add a load method to OptimizedNullArrayDumpLongColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayLongColumnBinaryMaker.java

Add a load method to OptimizedNullArrayLongColumnBinaryMaker.
In TestLongPrimitiveColumn.

Add a load method to OptimizedNullArrayLongColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/RleLongColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestLongPrimitiveColumn.java

Add a load method to RleLongColumnBinaryMaker.
In TestLongPrimitiveColumn.

Add a load method to RleLongColumnBinaryMaker

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestBytePrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestIntegerPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestShortPrimitiveColumn.java

Modify some black box tests.
In TestBytePrimitiveColumn, TestIntegerPrimitiveColumn, TestShortPrimitiveColumn.

Modify some black box tests

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/DictionaryRleStringColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestStringPrimitiveColumn.java

Add a load method to DictionaryRleStringColumnBinaryMaker.
In TestStringPrimitiveColumn.

Add a load method to DictionaryRleStringColumnBinaryMaker

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/OptimizedNullArrayDumpDoubleColumnBinaryMaker.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestDoublePrimitiveColumn.java

Use repetitions instead of loadindex.
Tested in TestDoublePrimitiveColumn.

Use repetitions instead of loadindex

---

pom.xml

Version change to 2.0.0.

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestBooleanPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestBytePrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestBytesPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestDoublePrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestFloatPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestIntegerPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestLongPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestShortPrimitiveColumn.java
src/test/java/jp/co/yahoo/yosegi/blackbox/TestStringPrimitiveColumn.java

Change blackbox toColumn function so that spread size can be given from the outside.
In blackbox tests.

Change blackbox toColumn function

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/MaxLengthBasedArrayColumnBinaryMaker.java

Fixed a bug that didn't continue in the loop.

Fixed a bug that didn't continue in the loop.

---

src/test/java/jp/co/yahoo/yosegi/blackbox/TestArrayColumn.java

Add a test for the case that loadSize is larger than rowCount.
In TestArrayColumn.

Add a test for #170

---

src/main/java/jp/co/yahoo/yosegi/binary/maker/DictionaryRleStringColumnBinaryMaker.java

Change the loader of DictionaryRleStringColumnBinaryMaker.loadFromColumnBinary to IDictionaryLoader.
And deprecate IDictionary.
In TestStringPrimitiveColumn.

Change the loader of DictionaryRleStringColumnBinaryMaker.loadFromColumnBinary to IDictionaryLoader
